languageCode: 'en-GB'
title: 'Greg Holmes'
theme: 'greboid.com'
publishDir: '../public'
params:
  BlogEnabled: false
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog
      weight: 2
markup:
  highlight:
    lineNos: false
    noClasses: false
