name = "greboid.com"
license = "MIT"
licenselink = "https://github.com/greboid/greboid.com/blob/master/LICENSE"
description = ""
homepage = "https://greboid.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Greboid"
  homepage = "https://greboid.com"